services:
  web:
    build:
      dockerfile: Dockerfile.test
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/web_drive/app
      - ./tests:/web_drive/tests

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports: "${POSTGRES_PORT}:${POSTGRES_PORT}" # If you locally connect

